name: Consumer build image and deploy

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'lab1/consumer/*.py'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'lab1/consumer/*.py'
  workflow_dispatch:

jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
      
  linter:
    runs-on: ubuntu-latest
    env:
      EVENT_HUB_CONNECTION_STR: ${{ secrets.EVENT_HUB_CONNECTION_STR }}
      EVENT_HUB_NAME: ${{ secrets.EVENT_HUB_NAME }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_SECRET_KEY: ${{ secrets.REDDIT_SECRET_KEY }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: lab1/consumer
      - name: Run Linter
        run: |
          pylint consumer
        working-directory: lab1/consumer
          

  azure_and_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/lab1/consumer/
          acrName: tpioucontainerregistry
          dockerfilePath: Dockerfile
          containerAppName: consumer-lab1
          resourceGroup: fervjestina
          imageToBuild: tpioucontainerregistry.azurecr.io/consumer-lab1:latest
